name: revier_app_client
description: "Revier App Client"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  material_color_utilities: ^0.11.1
  google_fonts: ^6.1.0
  material_symbols_icons: ^4.2810.0
  
  # Riverpod
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3
  
  # Supabase
  supabase_flutter: ^2.8.4
  supabase_auth_ui: ^0.5.4
  postgrest: ^2.4.1
  realtime_client: ^2.4.2
  supabase: ^2.6.3
  gotrue: ^2.11.1
  
  # Translations
  intl: ^0.19.0
  
  # Freezed
  freezed_annotation: ^3.0.0
  
  # Brick for offline-first
  brick_core: ^2.0.0
  brick_sqlite: ^4.0.0
  brick_offline_first_with_supabase: ^2.0.0
  sqflite: ^2.4.2
  uuid: ^4.2.1
  path: ^1.8.3
  connectivity_plus: ^6.1.3
  brick_supabase: ^2.0.0
  mapbox_maps_flutter: ^2.6.1
  google_sign_in: ^6.3.0
  flutter_native_splash: ^2.4.5
  image_picker: ^1.1.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

  # OpenAPI generator
  build_runner: ^2.4.7
  chopper_generator: ^8.1.0
  json_serializable: ^6.7.1

  # Riverpod
  riverpod_generator: ^2.6.5

  # Freezed
  freezed: ^3.0.3
  
  # Brick code generation
  brick_offline_first_with_supabase_build: ^2.0.0
  brick_build: ^4.0.0
  mockito: ^5.4.3


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logo/
    
  # url_strategy:
  #   android:
  #     scheme: de.revierapp.client
  #     host: login-callback
  #   ios:
  #     scheme: de.revierapp.client
  #     host: login-callback

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/revierapp_android.png" # Will be created from SVG
  image_path_ios: "assets/logo/revierapp_ios.png" # Will be created from SVG
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/revierapp_foreground.png" # Will be created from SVG
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#2C3532" # Brand color
  image: assets/logo/revierapp_splash.png # White version of the logo for visibility
  color_dark: "#2C3532"
  image_dark: assets/logo/revierapp_splash.png
  
  android_12:
    image: assets/logo/revierapp_splash.png
    icon_background_color: "#2C3532"
    image_dark: assets/logo/revierapp_splash.png
    icon_background_color_dark: "#2C3532"
  
  ios: true
  web: false
  android: true
