// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250319173628_up = [
  InsertTable('WeatherCondition'),
  InsertTable('Animal'),
  InsertTable('HuntingGround'),
  InsertTable('Weapon'),
  InsertTable('AllowedCaliber'),
  InsertTable('Camera'),
  InsertTable('Country'),
  InsertTable('Species'),
  InsertTable('Tag'),
  InsertTable('Caliber'),
  InsertTable('HuntingSeason'),
  InsertTable('FederalState'),
  InsertTable('Shooting'),
  InsertTable('UploadUnprocessedMedia'),
  InsertTable('Media'),
  InsertTable('HuntingGroundUserRole'),
  InsertTable('Sighting'),
  InsertTable('Upload'),
  InsertTable('SightingTag'),
  InsertTable('AnimalFilter'),
  InsertTable('UploadMedia'),
  InsertColumn('id', Column.varchar, onTable: 'WeatherCondition', unique: true),
  InsertColumn('wind_direction', Column.integer, onTable: 'WeatherCondition'),
  InsertColumn('wind_speed', Column.Double, onTable: 'WeatherCondition'),
  InsertColumn('temperature', Column.Double, onTable: 'WeatherCondition'),
  InsertColumn('air_pressure', Column.Double, onTable: 'WeatherCondition'),
  InsertColumn('precipitation', Column.Double, onTable: 'WeatherCondition'),
  InsertColumn('ground_conditions', Column.varchar, onTable: 'WeatherCondition'),
  InsertColumn('moon_phase', Column.varchar, onTable: 'WeatherCondition'),
  InsertColumn('timestamp', Column.datetime, onTable: 'WeatherCondition'),
  InsertColumn('created_at', Column.datetime, onTable: 'WeatherCondition'),
  InsertColumn('updated_at', Column.datetime, onTable: 'WeatherCondition'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'WeatherCondition'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'WeatherCondition'),
  InsertColumn('id', Column.varchar, onTable: 'Animal', unique: true),
  InsertForeignKey('Animal', 'HuntingGround', foreignKeyColumn: 'hunting_ground_HuntingGround_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('hunting_ground_id', Column.varchar, onTable: 'Animal'),
  InsertColumn('name', Column.varchar, onTable: 'Animal'),
  InsertColumn('dead', Column.boolean, onTable: 'Animal'),
  InsertColumn('age', Column.Double, onTable: 'Animal'),
  InsertColumn('weight', Column.Double, onTable: 'Animal'),
  InsertColumn('abnormalities', Column.varchar, onTable: 'Animal'),
  InsertColumn('shooting_priority', Column.integer, onTable: 'Animal'),
  InsertColumn('notes', Column.varchar, onTable: 'Animal'),
  InsertForeignKey('Animal', 'Shooting', foreignKeyColumn: 'shooting_Shooting_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('shooting_id', Column.varchar, onTable: 'Animal'),
  InsertForeignKey('Animal', 'Species', foreignKeyColumn: 'species_Species_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('species_id', Column.varchar, onTable: 'Animal'),
  InsertColumn('custom_color', Column.integer, onTable: 'Animal'),
  InsertColumn('created_at', Column.datetime, onTable: 'Animal'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Animal'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Animal'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Animal'),
  InsertColumn('id', Column.varchar, onTable: 'HuntingGround', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'HuntingGround'),
  InsertForeignKey('HuntingGround', 'FederalState', foreignKeyColumn: 'federal_state_FederalState_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('federal_state_id', Column.varchar, onTable: 'HuntingGround'),
  InsertColumn('created_at', Column.datetime, onTable: 'HuntingGround'),
  InsertColumn('updated_at', Column.datetime, onTable: 'HuntingGround'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'HuntingGround'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'HuntingGround'),
  InsertColumn('id', Column.varchar, onTable: 'Weapon', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Weapon'),
  InsertColumn('user', Column.varchar, onTable: 'Weapon'),
  InsertForeignKey('Weapon', 'Caliber', foreignKeyColumn: 'default_caliber_Caliber_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('created_at', Column.datetime, onTable: 'Weapon'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Weapon'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Weapon'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Weapon'),
  InsertColumn('id', Column.varchar, onTable: 'AllowedCaliber', unique: true),
  InsertColumn('valid_from', Column.datetime, onTable: 'AllowedCaliber'),
  InsertColumn('valid_until', Column.datetime, onTable: 'AllowedCaliber'),
  InsertForeignKey('AllowedCaliber', 'Species', foreignKeyColumn: 'species_Species_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('species_id', Column.varchar, onTable: 'AllowedCaliber'),
  InsertForeignKey('AllowedCaliber', 'Caliber', foreignKeyColumn: 'caliber_Caliber_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('caliber_id', Column.varchar, onTable: 'AllowedCaliber'),
  InsertForeignKey('AllowedCaliber', 'FederalState', foreignKeyColumn: 'federal_state_FederalState_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('federal_state_id', Column.varchar, onTable: 'AllowedCaliber'),
  InsertColumn('created_at', Column.datetime, onTable: 'AllowedCaliber'),
  InsertColumn('updated_at', Column.datetime, onTable: 'AllowedCaliber'),
  InsertColumn('id', Column.varchar, onTable: 'Camera', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Camera'),
  InsertColumn('latitude', Column.Double, onTable: 'Camera'),
  InsertColumn('longitude', Column.Double, onTable: 'Camera'),
  InsertColumn('created_at', Column.datetime, onTable: 'Camera'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Camera'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Camera'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Camera'),
  InsertColumn('id', Column.varchar, onTable: 'Country', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Country'),
  InsertColumn('id', Column.varchar, onTable: 'Species', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Species'),
  InsertColumn('is_pest', Column.boolean, onTable: 'Species'),
  InsertColumn('created_at', Column.datetime, onTable: 'Species'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Species'),
  InsertColumn('id', Column.varchar, onTable: 'Tag', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Tag'),
  InsertColumn('color', Column.varchar, onTable: 'Tag'),
  InsertColumn('created_at', Column.datetime, onTable: 'Tag'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Tag'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Tag'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Tag'),
  InsertColumn('id', Column.varchar, onTable: 'Caliber', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Caliber'),
  InsertColumn('created_at', Column.datetime, onTable: 'Caliber'),
  InsertColumn('created_by', Column.varchar, onTable: 'Caliber'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Caliber'),
  InsertColumn('updated_by', Column.varchar, onTable: 'Caliber'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Caliber'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Caliber'),
  InsertColumn('id', Column.varchar, onTable: 'HuntingSeason', unique: true),
  InsertForeignKey('HuntingSeason', 'FederalState', foreignKeyColumn: 'federal_state_FederalState_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('federal_state_id', Column.varchar, onTable: 'HuntingSeason'),
  InsertForeignKey('HuntingSeason', 'Species', foreignKeyColumn: 'species_Species_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('species_id', Column.varchar, onTable: 'HuntingSeason'),
  InsertColumn('start_date', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('end_date', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('animal_age_min', Column.integer, onTable: 'HuntingSeason'),
  InsertColumn('valid_from', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('valid_until', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('updated_at', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('created_at', Column.datetime, onTable: 'HuntingSeason'),
  InsertColumn('id', Column.varchar, onTable: 'FederalState', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'FederalState'),
  InsertForeignKey('FederalState', 'Country', foreignKeyColumn: 'country_Country_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('country_id', Column.varchar, onTable: 'FederalState'),
  InsertColumn('id', Column.varchar, onTable: 'Shooting', unique: true),
  InsertColumn('shot_by', Column.varchar, onTable: 'Shooting'),
  InsertForeignKey('Shooting', 'Weapon', foreignKeyColumn: 'weapon_Weapon_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('Shooting', 'Caliber', foreignKeyColumn: 'caliber_Caliber_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('distance', Column.Double, onTable: 'Shooting'),
  InsertColumn('hit_location', Column.varchar, onTable: 'Shooting'),
  InsertColumn('shot_count', Column.integer, onTable: 'Shooting'),
  InsertColumn('notes', Column.varchar, onTable: 'Shooting'),
  InsertColumn('shot_at', Column.datetime, onTable: 'Shooting'),
  InsertColumn('created_at', Column.datetime, onTable: 'Shooting'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Shooting'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Shooting'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Shooting'),
  InsertColumn('id', Column.varchar, onTable: 'UploadUnprocessedMedia', unique: true),
  InsertForeignKey('UploadUnprocessedMedia', 'Upload', foreignKeyColumn: 'upload_Upload_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('upload_id', Column.varchar, onTable: 'UploadUnprocessedMedia'),
  InsertForeignKey('UploadUnprocessedMedia', 'Media', foreignKeyColumn: 'media_Media_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('media_id', Column.varchar, onTable: 'UploadUnprocessedMedia'),
  InsertColumn('id', Column.varchar, onTable: 'Media', unique: true),
  InsertColumn('media_type', Column.varchar, onTable: 'Media'),
  InsertColumn('remote_file_path', Column.varchar, onTable: 'Media'),
  InsertColumn('local_file_path', Column.varchar, onTable: 'Media'),
  InsertColumn('time_offset', Column.integer, onTable: 'Media'),
  InsertColumn('timestamp_original', Column.datetime, onTable: 'Media'),
  InsertColumn('timestamp', Column.datetime, onTable: 'Media'),
  InsertColumn('created_by', Column.varchar, onTable: 'Media'),
  InsertColumn('created_by_id', Column.varchar, onTable: 'Media'),
  InsertColumn('updated_by', Column.varchar, onTable: 'Media'),
  InsertColumn('updated_by_id', Column.varchar, onTable: 'Media'),
  InsertColumn('deleted_by', Column.varchar, onTable: 'Media'),
  InsertColumn('deleted_by_id', Column.varchar, onTable: 'Media'),
  InsertColumn('created_at', Column.datetime, onTable: 'Media'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Media'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Media'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Media'),
  InsertColumn('id', Column.varchar, onTable: 'HuntingGroundUserRole', unique: true),
  InsertColumn('user', Column.varchar, onTable: 'HuntingGroundUserRole'),
  InsertColumn('user_id', Column.varchar, onTable: 'HuntingGroundUserRole'),
  InsertForeignKey('HuntingGroundUserRole', 'HuntingGround', foreignKeyColumn: 'hunting_ground_HuntingGround_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('hunting_ground_id', Column.varchar, onTable: 'HuntingGroundUserRole'),
  InsertColumn('role', Column.varchar, onTable: 'HuntingGroundUserRole'),
  InsertColumn('id', Column.varchar, onTable: 'Sighting', unique: true),
  InsertForeignKey('Sighting', 'Species', foreignKeyColumn: 'species_Species_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('species_id', Column.varchar, onTable: 'Sighting'),
  InsertColumn('group_type', Column.varchar, onTable: 'Sighting'),
  InsertColumn('animal_count', Column.integer, onTable: 'Sighting'),
  InsertColumn('animal_count_precision', Column.integer, onTable: 'Sighting'),
  InsertForeignKey('Sighting', 'WeatherCondition', foreignKeyColumn: 'weather_condition_WeatherCondition_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('weather_condition_id', Column.varchar, onTable: 'Sighting'),
  InsertForeignKey('Sighting', 'Camera', foreignKeyColumn: 'camera_Camera_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('camera_id', Column.varchar, onTable: 'Sighting'),
  InsertForeignKey('Sighting', 'Upload', foreignKeyColumn: 'upload_Upload_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('upload_id', Column.varchar, onTable: 'Sighting'),
  InsertColumn('latitude', Column.Double, onTable: 'Sighting'),
  InsertColumn('longitude', Column.Double, onTable: 'Sighting'),
  InsertColumn('sighting_start', Column.datetime, onTable: 'Sighting'),
  InsertColumn('sighting_end', Column.datetime, onTable: 'Sighting'),
  InsertColumn('created_at', Column.datetime, onTable: 'Sighting'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Sighting'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Sighting'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Sighting'),
  InsertColumn('id', Column.varchar, onTable: 'Upload', unique: true),
  InsertColumn('status', Column.varchar, onTable: 'Upload'),
  InsertForeignKey('Upload', 'Camera', foreignKeyColumn: 'camera_Camera_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('camera_id', Column.varchar, onTable: 'Upload'),
  InsertColumn('latitude', Column.Double, onTable: 'Upload'),
  InsertColumn('longitude', Column.Double, onTable: 'Upload'),
  InsertColumn('created_by', Column.varchar, onTable: 'Upload'),
  InsertColumn('created_by_id', Column.varchar, onTable: 'Upload'),
  InsertColumn('updated_by', Column.varchar, onTable: 'Upload'),
  InsertColumn('updated_by_id', Column.varchar, onTable: 'Upload'),
  InsertColumn('deleted_by', Column.varchar, onTable: 'Upload'),
  InsertColumn('deleted_by_id', Column.varchar, onTable: 'Upload'),
  InsertColumn('created_at', Column.datetime, onTable: 'Upload'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Upload'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Upload'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'Upload'),
  InsertColumn('id', Column.varchar, onTable: 'SightingTag', unique: true),
  InsertForeignKey('SightingTag', 'Sighting', foreignKeyColumn: 'sighting_Sighting_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('sighting_id', Column.varchar, onTable: 'SightingTag'),
  InsertForeignKey('SightingTag', 'Tag', foreignKeyColumn: 'tag_Tag_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('tag_id', Column.varchar, onTable: 'SightingTag'),
  InsertColumn('id', Column.varchar, onTable: 'AnimalFilter', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'AnimalFilter'),
  InsertForeignKey('AnimalFilter', 'HuntingGround', foreignKeyColumn: 'hunting_ground_HuntingGround_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('hunting_ground_id', Column.varchar, onTable: 'AnimalFilter'),
  InsertColumn('animal_count', Column.integer, onTable: 'AnimalFilter'),
  InsertColumn('animal_count_type', Column.varchar, onTable: 'AnimalFilter'),
  InsertForeignKey('AnimalFilter', 'Species', foreignKeyColumn: 'species_Species_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('species_id', Column.varchar, onTable: 'AnimalFilter'),
  InsertColumn('custom_color', Column.integer, onTable: 'AnimalFilter'),
  InsertColumn('created_at', Column.datetime, onTable: 'AnimalFilter'),
  InsertColumn('updated_at', Column.datetime, onTable: 'AnimalFilter'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'AnimalFilter'),
  InsertColumn('is_deleted', Column.boolean, onTable: 'AnimalFilter'),
  InsertColumn('id', Column.varchar, onTable: 'UploadMedia', unique: true),
  InsertForeignKey('UploadMedia', 'Upload', foreignKeyColumn: 'upload_Upload_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('upload_id', Column.varchar, onTable: 'UploadMedia'),
  InsertForeignKey('UploadMedia', 'Media', foreignKeyColumn: 'media_Media_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('media_id', Column.varchar, onTable: 'UploadMedia'),
  CreateIndex(columns: ['id'], onTable: 'WeatherCondition', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Animal', unique: true),
  CreateIndex(columns: ['id'], onTable: 'HuntingGround', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Weapon', unique: true),
  CreateIndex(columns: ['id'], onTable: 'AllowedCaliber', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Camera', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Country', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Species', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Tag', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Caliber', unique: true),
  CreateIndex(columns: ['id'], onTable: 'HuntingSeason', unique: true),
  CreateIndex(columns: ['id'], onTable: 'FederalState', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Shooting', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UploadUnprocessedMedia', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Media', unique: true),
  CreateIndex(columns: ['id'], onTable: 'HuntingGroundUserRole', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Sighting', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Upload', unique: true),
  CreateIndex(columns: ['id'], onTable: 'SightingTag', unique: true),
  CreateIndex(columns: ['id'], onTable: 'AnimalFilter', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UploadMedia', unique: true)
];

const List<MigrationCommand> _migration_20250319173628_down = [
  DropTable('WeatherCondition'),
  DropTable('Animal'),
  DropTable('HuntingGround'),
  DropTable('Weapon'),
  DropTable('AllowedCaliber'),
  DropTable('Camera'),
  DropTable('Country'),
  DropTable('Species'),
  DropTable('Tag'),
  DropTable('Caliber'),
  DropTable('HuntingSeason'),
  DropTable('FederalState'),
  DropTable('Shooting'),
  DropTable('UploadUnprocessedMedia'),
  DropTable('Media'),
  DropTable('HuntingGroundUserRole'),
  DropTable('Sighting'),
  DropTable('Upload'),
  DropTable('SightingTag'),
  DropTable('AnimalFilter'),
  DropTable('UploadMedia'),
  DropColumn('id', onTable: 'WeatherCondition'),
  DropColumn('wind_direction', onTable: 'WeatherCondition'),
  DropColumn('wind_speed', onTable: 'WeatherCondition'),
  DropColumn('temperature', onTable: 'WeatherCondition'),
  DropColumn('air_pressure', onTable: 'WeatherCondition'),
  DropColumn('precipitation', onTable: 'WeatherCondition'),
  DropColumn('ground_conditions', onTable: 'WeatherCondition'),
  DropColumn('moon_phase', onTable: 'WeatherCondition'),
  DropColumn('timestamp', onTable: 'WeatherCondition'),
  DropColumn('created_at', onTable: 'WeatherCondition'),
  DropColumn('updated_at', onTable: 'WeatherCondition'),
  DropColumn('deleted_at', onTable: 'WeatherCondition'),
  DropColumn('is_deleted', onTable: 'WeatherCondition'),
  DropColumn('id', onTable: 'Animal'),
  DropColumn('hunting_ground_HuntingGround_brick_id', onTable: 'Animal'),
  DropColumn('hunting_ground_id', onTable: 'Animal'),
  DropColumn('name', onTable: 'Animal'),
  DropColumn('dead', onTable: 'Animal'),
  DropColumn('age', onTable: 'Animal'),
  DropColumn('weight', onTable: 'Animal'),
  DropColumn('abnormalities', onTable: 'Animal'),
  DropColumn('shooting_priority', onTable: 'Animal'),
  DropColumn('notes', onTable: 'Animal'),
  DropColumn('shooting_Shooting_brick_id', onTable: 'Animal'),
  DropColumn('shooting_id', onTable: 'Animal'),
  DropColumn('species_Species_brick_id', onTable: 'Animal'),
  DropColumn('species_id', onTable: 'Animal'),
  DropColumn('custom_color', onTable: 'Animal'),
  DropColumn('created_at', onTable: 'Animal'),
  DropColumn('updated_at', onTable: 'Animal'),
  DropColumn('deleted_at', onTable: 'Animal'),
  DropColumn('is_deleted', onTable: 'Animal'),
  DropColumn('id', onTable: 'HuntingGround'),
  DropColumn('name', onTable: 'HuntingGround'),
  DropColumn('federal_state_FederalState_brick_id', onTable: 'HuntingGround'),
  DropColumn('federal_state_id', onTable: 'HuntingGround'),
  DropColumn('created_at', onTable: 'HuntingGround'),
  DropColumn('updated_at', onTable: 'HuntingGround'),
  DropColumn('deleted_at', onTable: 'HuntingGround'),
  DropColumn('is_deleted', onTable: 'HuntingGround'),
  DropColumn('id', onTable: 'Weapon'),
  DropColumn('name', onTable: 'Weapon'),
  DropColumn('user', onTable: 'Weapon'),
  DropColumn('default_caliber_Caliber_brick_id', onTable: 'Weapon'),
  DropColumn('created_at', onTable: 'Weapon'),
  DropColumn('updated_at', onTable: 'Weapon'),
  DropColumn('deleted_at', onTable: 'Weapon'),
  DropColumn('is_deleted', onTable: 'Weapon'),
  DropColumn('id', onTable: 'AllowedCaliber'),
  DropColumn('valid_from', onTable: 'AllowedCaliber'),
  DropColumn('valid_until', onTable: 'AllowedCaliber'),
  DropColumn('species_Species_brick_id', onTable: 'AllowedCaliber'),
  DropColumn('species_id', onTable: 'AllowedCaliber'),
  DropColumn('caliber_Caliber_brick_id', onTable: 'AllowedCaliber'),
  DropColumn('caliber_id', onTable: 'AllowedCaliber'),
  DropColumn('federal_state_FederalState_brick_id', onTable: 'AllowedCaliber'),
  DropColumn('federal_state_id', onTable: 'AllowedCaliber'),
  DropColumn('created_at', onTable: 'AllowedCaliber'),
  DropColumn('updated_at', onTable: 'AllowedCaliber'),
  DropColumn('id', onTable: 'Camera'),
  DropColumn('name', onTable: 'Camera'),
  DropColumn('latitude', onTable: 'Camera'),
  DropColumn('longitude', onTable: 'Camera'),
  DropColumn('created_at', onTable: 'Camera'),
  DropColumn('updated_at', onTable: 'Camera'),
  DropColumn('deleted_at', onTable: 'Camera'),
  DropColumn('is_deleted', onTable: 'Camera'),
  DropColumn('id', onTable: 'Country'),
  DropColumn('name', onTable: 'Country'),
  DropColumn('id', onTable: 'Species'),
  DropColumn('name', onTable: 'Species'),
  DropColumn('is_pest', onTable: 'Species'),
  DropColumn('created_at', onTable: 'Species'),
  DropColumn('updated_at', onTable: 'Species'),
  DropColumn('id', onTable: 'Tag'),
  DropColumn('name', onTable: 'Tag'),
  DropColumn('color', onTable: 'Tag'),
  DropColumn('created_at', onTable: 'Tag'),
  DropColumn('updated_at', onTable: 'Tag'),
  DropColumn('deleted_at', onTable: 'Tag'),
  DropColumn('is_deleted', onTable: 'Tag'),
  DropColumn('id', onTable: 'Caliber'),
  DropColumn('name', onTable: 'Caliber'),
  DropColumn('created_at', onTable: 'Caliber'),
  DropColumn('created_by', onTable: 'Caliber'),
  DropColumn('updated_at', onTable: 'Caliber'),
  DropColumn('updated_by', onTable: 'Caliber'),
  DropColumn('deleted_at', onTable: 'Caliber'),
  DropColumn('is_deleted', onTable: 'Caliber'),
  DropColumn('id', onTable: 'HuntingSeason'),
  DropColumn('federal_state_FederalState_brick_id', onTable: 'HuntingSeason'),
  DropColumn('federal_state_id', onTable: 'HuntingSeason'),
  DropColumn('species_Species_brick_id', onTable: 'HuntingSeason'),
  DropColumn('species_id', onTable: 'HuntingSeason'),
  DropColumn('start_date', onTable: 'HuntingSeason'),
  DropColumn('end_date', onTable: 'HuntingSeason'),
  DropColumn('animal_age_min', onTable: 'HuntingSeason'),
  DropColumn('valid_from', onTable: 'HuntingSeason'),
  DropColumn('valid_until', onTable: 'HuntingSeason'),
  DropColumn('updated_at', onTable: 'HuntingSeason'),
  DropColumn('created_at', onTable: 'HuntingSeason'),
  DropColumn('id', onTable: 'FederalState'),
  DropColumn('name', onTable: 'FederalState'),
  DropColumn('country_Country_brick_id', onTable: 'FederalState'),
  DropColumn('country_id', onTable: 'FederalState'),
  DropColumn('id', onTable: 'Shooting'),
  DropColumn('shot_by', onTable: 'Shooting'),
  DropColumn('weapon_Weapon_brick_id', onTable: 'Shooting'),
  DropColumn('caliber_Caliber_brick_id', onTable: 'Shooting'),
  DropColumn('distance', onTable: 'Shooting'),
  DropColumn('hit_location', onTable: 'Shooting'),
  DropColumn('shot_count', onTable: 'Shooting'),
  DropColumn('notes', onTable: 'Shooting'),
  DropColumn('shot_at', onTable: 'Shooting'),
  DropColumn('created_at', onTable: 'Shooting'),
  DropColumn('updated_at', onTable: 'Shooting'),
  DropColumn('deleted_at', onTable: 'Shooting'),
  DropColumn('is_deleted', onTable: 'Shooting'),
  DropColumn('id', onTable: 'UploadUnprocessedMedia'),
  DropColumn('upload_Upload_brick_id', onTable: 'UploadUnprocessedMedia'),
  DropColumn('upload_id', onTable: 'UploadUnprocessedMedia'),
  DropColumn('media_Media_brick_id', onTable: 'UploadUnprocessedMedia'),
  DropColumn('media_id', onTable: 'UploadUnprocessedMedia'),
  DropColumn('id', onTable: 'Media'),
  DropColumn('media_type', onTable: 'Media'),
  DropColumn('remote_file_path', onTable: 'Media'),
  DropColumn('local_file_path', onTable: 'Media'),
  DropColumn('time_offset', onTable: 'Media'),
  DropColumn('timestamp_original', onTable: 'Media'),
  DropColumn('timestamp', onTable: 'Media'),
  DropColumn('created_by', onTable: 'Media'),
  DropColumn('created_by_id', onTable: 'Media'),
  DropColumn('updated_by', onTable: 'Media'),
  DropColumn('updated_by_id', onTable: 'Media'),
  DropColumn('deleted_by', onTable: 'Media'),
  DropColumn('deleted_by_id', onTable: 'Media'),
  DropColumn('created_at', onTable: 'Media'),
  DropColumn('updated_at', onTable: 'Media'),
  DropColumn('deleted_at', onTable: 'Media'),
  DropColumn('is_deleted', onTable: 'Media'),
  DropColumn('id', onTable: 'HuntingGroundUserRole'),
  DropColumn('user', onTable: 'HuntingGroundUserRole'),
  DropColumn('user_id', onTable: 'HuntingGroundUserRole'),
  DropColumn('hunting_ground_HuntingGround_brick_id', onTable: 'HuntingGroundUserRole'),
  DropColumn('hunting_ground_id', onTable: 'HuntingGroundUserRole'),
  DropColumn('role', onTable: 'HuntingGroundUserRole'),
  DropColumn('id', onTable: 'Sighting'),
  DropColumn('species_Species_brick_id', onTable: 'Sighting'),
  DropColumn('species_id', onTable: 'Sighting'),
  DropColumn('group_type', onTable: 'Sighting'),
  DropColumn('animal_count', onTable: 'Sighting'),
  DropColumn('animal_count_precision', onTable: 'Sighting'),
  DropColumn('weather_condition_WeatherCondition_brick_id', onTable: 'Sighting'),
  DropColumn('weather_condition_id', onTable: 'Sighting'),
  DropColumn('camera_Camera_brick_id', onTable: 'Sighting'),
  DropColumn('camera_id', onTable: 'Sighting'),
  DropColumn('upload_Upload_brick_id', onTable: 'Sighting'),
  DropColumn('upload_id', onTable: 'Sighting'),
  DropColumn('latitude', onTable: 'Sighting'),
  DropColumn('longitude', onTable: 'Sighting'),
  DropColumn('sighting_start', onTable: 'Sighting'),
  DropColumn('sighting_end', onTable: 'Sighting'),
  DropColumn('created_at', onTable: 'Sighting'),
  DropColumn('updated_at', onTable: 'Sighting'),
  DropColumn('deleted_at', onTable: 'Sighting'),
  DropColumn('is_deleted', onTable: 'Sighting'),
  DropColumn('id', onTable: 'Upload'),
  DropColumn('status', onTable: 'Upload'),
  DropColumn('camera_Camera_brick_id', onTable: 'Upload'),
  DropColumn('camera_id', onTable: 'Upload'),
  DropColumn('latitude', onTable: 'Upload'),
  DropColumn('longitude', onTable: 'Upload'),
  DropColumn('created_by', onTable: 'Upload'),
  DropColumn('created_by_id', onTable: 'Upload'),
  DropColumn('updated_by', onTable: 'Upload'),
  DropColumn('updated_by_id', onTable: 'Upload'),
  DropColumn('deleted_by', onTable: 'Upload'),
  DropColumn('deleted_by_id', onTable: 'Upload'),
  DropColumn('created_at', onTable: 'Upload'),
  DropColumn('updated_at', onTable: 'Upload'),
  DropColumn('deleted_at', onTable: 'Upload'),
  DropColumn('is_deleted', onTable: 'Upload'),
  DropColumn('id', onTable: 'SightingTag'),
  DropColumn('sighting_Sighting_brick_id', onTable: 'SightingTag'),
  DropColumn('sighting_id', onTable: 'SightingTag'),
  DropColumn('tag_Tag_brick_id', onTable: 'SightingTag'),
  DropColumn('tag_id', onTable: 'SightingTag'),
  DropColumn('id', onTable: 'AnimalFilter'),
  DropColumn('name', onTable: 'AnimalFilter'),
  DropColumn('hunting_ground_HuntingGround_brick_id', onTable: 'AnimalFilter'),
  DropColumn('hunting_ground_id', onTable: 'AnimalFilter'),
  DropColumn('animal_count', onTable: 'AnimalFilter'),
  DropColumn('animal_count_type', onTable: 'AnimalFilter'),
  DropColumn('species_Species_brick_id', onTable: 'AnimalFilter'),
  DropColumn('species_id', onTable: 'AnimalFilter'),
  DropColumn('custom_color', onTable: 'AnimalFilter'),
  DropColumn('created_at', onTable: 'AnimalFilter'),
  DropColumn('updated_at', onTable: 'AnimalFilter'),
  DropColumn('deleted_at', onTable: 'AnimalFilter'),
  DropColumn('is_deleted', onTable: 'AnimalFilter'),
  DropColumn('id', onTable: 'UploadMedia'),
  DropColumn('upload_Upload_brick_id', onTable: 'UploadMedia'),
  DropColumn('upload_id', onTable: 'UploadMedia'),
  DropColumn('media_Media_brick_id', onTable: 'UploadMedia'),
  DropColumn('media_id', onTable: 'UploadMedia'),
  DropIndex('index_WeatherCondition_on_id'),
  DropIndex('index_Animal_on_id'),
  DropIndex('index_HuntingGround_on_id'),
  DropIndex('index_Weapon_on_id'),
  DropIndex('index_AllowedCaliber_on_id'),
  DropIndex('index_Camera_on_id'),
  DropIndex('index_Country_on_id'),
  DropIndex('index_Species_on_id'),
  DropIndex('index_Tag_on_id'),
  DropIndex('index_Caliber_on_id'),
  DropIndex('index_HuntingSeason_on_id'),
  DropIndex('index_FederalState_on_id'),
  DropIndex('index_Shooting_on_id'),
  DropIndex('index_UploadUnprocessedMedia_on_id'),
  DropIndex('index_Media_on_id'),
  DropIndex('index_HuntingGroundUserRole_on_id'),
  DropIndex('index_Sighting_on_id'),
  DropIndex('index_Upload_on_id'),
  DropIndex('index_SightingTag_on_id'),
  DropIndex('index_AnimalFilter_on_id'),
  DropIndex('index_UploadMedia_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250319173628',
  up: _migration_20250319173628_up,
  down: _migration_20250319173628_down,
)
class Migration20250319173628 extends Migration {
  const Migration20250319173628()
    : super(
        version: 20250319173628,
        up: _migration_20250319173628_up,
        down: _migration_20250319173628_down,
      );
}
