// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20250330130007.migration.dart';
part '20250330203840.migration.dart';
part '20250319180548.migration.dart';
part '20250319173628.migration.dart';
part '20250330134049.migration.dart';
part '20250319180222.migration.dart';
part '20250320152335.migration.dart';
part '20250319180854.migration.dart';
part '20250320170536.migration.dart';
part '20250330133526.migration.dart';
part '20250328164053.migration.dart';
part '20250330131421.migration.dart';
part '20250320161653.migration.dart';
part '20250330201026.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20250330130007(),
  const Migration20250330203840(),
  const Migration20250319180548(),
  const Migration20250319173628(),
  const Migration20250330134049(),
  const Migration20250319180222(),
  const Migration20250320152335(),
  const Migration20250319180854(),
  const Migration20250320170536(),
  const Migration20250330133526(),
  const Migration20250328164053(),
  const Migration20250330131421(),
  const Migration20250320161653(),
  const Migration20250330201026(),
};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  20250330203840,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'WeatherCondition',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('wind_direction', Column.integer),
        SchemaColumn('wind_speed', Column.Double),
        SchemaColumn('temperature', Column.Double),
        SchemaColumn('air_pressure', Column.Double),
        SchemaColumn('precipitation', Column.Double),
        SchemaColumn('ground_conditions', Column.varchar),
        SchemaColumn('moon_phase', Column.varchar),
        SchemaColumn('timestamp', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Animal',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('dead', Column.boolean),
        SchemaColumn('age', Column.Double),
        SchemaColumn('weight', Column.Double),
        SchemaColumn('abnormalities', Column.varchar),
        SchemaColumn('shooting_priority', Column.integer),
        SchemaColumn('notes', Column.varchar),
        SchemaColumn(
          'shooting_Shooting_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Shooting',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'species_Species_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Species',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('custom_color', Column.integer),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'HuntingGround',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn(
          'federal_state_FederalState_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'FederalState',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Weapon',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('user_id', Column.varchar),
        SchemaColumn(
          'default_caliber_Caliber_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Caliber',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'AllowedCaliber',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('valid_from', Column.datetime),
        SchemaColumn('valid_until', Column.datetime),
        SchemaColumn(
          'species_Species_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Species',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'caliber_Caliber_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Caliber',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'federal_state_FederalState_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'FederalState',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Camera',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Country',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Species',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('is_pest', Column.boolean),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Tag',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('color', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Caliber',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('created_by_id', Column.varchar),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('updated_by_id', Column.varchar),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'HuntingSeason',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'federal_state_FederalState_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'FederalState',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'species_Species_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Species',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('start_date', Column.datetime),
        SchemaColumn('end_date', Column.datetime),
        SchemaColumn('animal_age_min', Column.integer),
        SchemaColumn('valid_from', Column.datetime),
        SchemaColumn('valid_until', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'FederalState',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn(
          'country_Country_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Country',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Shooting',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('shot_by_id', Column.varchar),
        SchemaColumn(
          'weapon_Weapon_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Weapon',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'caliber_Caliber_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Caliber',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('distance', Column.Double),
        SchemaColumn('hit_location', Column.varchar),
        SchemaColumn('shot_count', Column.integer),
        SchemaColumn('notes', Column.varchar),
        SchemaColumn('shot_at', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'UploadUnprocessedMedia',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'upload_Upload_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Upload',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'media_Media_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Media',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Media',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('media_type', Column.varchar),
        SchemaColumn('remote_file_path', Column.varchar),
        SchemaColumn('local_file_path', Column.varchar),
        SchemaColumn('time_offset', Column.integer),
        SchemaColumn('timestamp_original', Column.datetime),
        SchemaColumn('timestamp', Column.datetime),
        SchemaColumn('created_by_id', Column.varchar),
        SchemaColumn('updated_by_id', Column.varchar),
        SchemaColumn('deleted_by_id', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'HuntingGroundUserRole',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('user_id', Column.varchar),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn('role', Column.varchar),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Sighting',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'species_Species_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Species',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('group_type', Column.varchar),
        SchemaColumn('animal_count', Column.integer),
        SchemaColumn('animal_count_precision', Column.integer),
        SchemaColumn(
          'weather_condition_WeatherCondition_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'WeatherCondition',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'camera_Camera_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Camera',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn(
          'upload_Upload_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Upload',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('sighting_start', Column.datetime),
        SchemaColumn('sighting_end', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Upload',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('status', Column.varchar),
        SchemaColumn(
          'camera_Camera_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Camera',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn('latitude', Column.Double),
        SchemaColumn('longitude', Column.Double),
        SchemaColumn('created_by_id', Column.varchar),
        SchemaColumn('updated_by_id', Column.varchar),
        SchemaColumn('deleted_by_id', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'SightingTag',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'sighting_Sighting_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Sighting',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'tag_Tag_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Tag',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'AnimalFilter',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn(
          'hunting_ground_HuntingGround_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'HuntingGround',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('hunting_ground_id', Column.varchar),
        SchemaColumn('animal_count', Column.integer),
        SchemaColumn('animal_count_type', Column.varchar),
        SchemaColumn(
          'species_Species_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Species',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('custom_color', Column.integer),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('is_deleted', Column.boolean),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'UploadMedia',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'upload_Upload_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Upload',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'media_Media_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Media',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
  },
);
